class CfpSphinx(object):
    """Pull data from CFP database and generate corresponding
    reStructuredText files into a Sphinx source path using templates.
    """

    def __init__(self):
        super(CfpSphinx, self).__init__()

        # source/cfp/index.rst
        self.gubernia_templ = textwrap.dedent("""
        .. autogenerated by cfp-sphinx.py

           :toctree:
        {members}
        """)
